name: Test
on:
  pull_request:
  push:
    branches:
      - master
      - 'renovate/*'
jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && !startsWith(github.head_ref, 'renovate/'))
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'yarn'
      - run: yarn
      - run: yarn test:ci
